name: Herve Lewis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-herve-lewis:

    runs-on: self-hosted

    steps:

      - name: Get Project Files Ownership
        run: sudo chown -R $USER:$USER /var/www/actions-runner/_work/hervelewis/

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3.8'
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: sudo chmod -R 777 storage bootstrap/cache
      - name: Install NPM
        run: sudo apt install npm -y

      - name: NPM Build
        run: sudo npm install && npm run build

      - name: Own Node Modules
        run: sudo chown -R $USER:$USER /var/www/actions-runner/_work/hervelewis/node_modules/

      - name: Create Database if Not Exists
        env:
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        run: |
          export MYSQL_PWD=$MYSQL_PASSWORD
          DB_EXISTS=$(mysql -u$MYSQL_USERNAME -e "SHOW DATABASES LIKE '$MYSQL_DATABASE';" | grep "$MYSQL_DATABASE" > /dev/null; echo $?)
          if [ $DB_EXISTS -eq 1 ]; then
            mysql -u$MYSQL_USERNAME -e "CREATE DATABASE $MYSQL_DATABASE;"
            echo "Database $MYSQL_DATABASE created."
          else
            echo "Database $MYSQL_DATABASE already exists. Skipping creation."
          fi

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        run: |
 #         sudo php artisan migrate:fresh --seed
 #         sudo php artisan test

#      - name: Install Apache
#        run: sudo apt-get install apache2 -y

      - name: Configure Apache Virtual Host
        run: |
          sudo bash -c 'cat > /etc/apache2/sites-available/hervelewis.allanmuzeya.com.conf <<EOF
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              ServerName hervelewis.allanmuzeya.com
              DocumentRoot /var/www/actions-runner/_work/hervelewis/public

              <Directory /var/www/actions-runner/_work/hervelewis/public>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog \${APACHE_LOG_DIR}/error.log
              CustomLog \${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
          EOF'

      - name: Enable Apache Virtual Host
        run: |
          sudo a2ensite hervelewis.allanmuzeya.com.conf
          sudo a2enmod rewrite
          sudo systemctl restart apache2

      - name: Return Project Files Ownership
        run: sudo chown -R www-data:www-data /var/www/actions-runner/_work/hervelewis/
